[alias]
cov = "llvm-cov --workspace --exclude cooper-web --exclude cooper-e2e --ignore-filename-regex (^|/)main\\.rs$|mock-server/src/lib\\.rs$"
cov-report = "llvm-cov report --ignore-filename-regex (^|/)main\\.rs$|mock-server/src/lib\\.rs$"
