[alias]
cov = "llvm-cov --workspace --exclude cooper-web --ignore-filename-regex (^|/)main\\.rs$|mock-server/src/lib\\.rs$"
cov-report = "llvm-cov report --ignore-filename-regex (^|/)main\\.rs$|mock-server/src/lib\\.rs$"
